#!/usr/bin/env bash

# Adding Brew to path
export PATH=/usr/local/bin:$PATH

source ${HOME}/.bash_functions
source ${HOME}/.bash_aliases

# Adding MacTeX to path
export PATH=/usr/local/texlive//2013/bin/x86_64-darwin/:$PATH
export CVS_RSH=ssh
export WORK=$HOME/workspace
alias cdw="cd $WORK"

# Add Java home
export JAVA_HOME=$(/usr/libexec/java_home)

# Adding module files
source /Users/aterrel/workspace/apps/Lmod/5.2/lmod/lmod/init/bash
module use $WORK/modulefiles
module load anaconda libdynd dynd-python blz datashape blaze 
module load andy

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='andy'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@github.com'

# Set my editor and git editor
export EDITOR="emacs -nw -q"
export GIT_EDITOR="emacs -nw -q"

# Set the path nginx
export NGINX_PATH='/opt/nginx'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

##
# Your previous /Users/aterrel/.bash_profile file was backed up as /Users/aterrel/.bash_profile.macports-saved_2014-07-19_at_08:03:00
##

# MacPorts Installer addition on 2014-07-19_at_08:03:00: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

