#!/usr/bin/env bash

# Adding Brew to path
export PATH=/usr/local/bin:$PATH

[ -e ${HOME}/.bash_functions ] && source ${HOME}/.bash_functions
[ -e ${HOME}/.bash_aliases ] && source ${HOME}/.bash_aliases

export CVS_RSH=ssh
export WORK=$HOME/workspace
alias cdw="cd $WORK"

# Anaconda 2.1.0 5
export PATH="/Users/aterrel/workspace/apps/anaconda/py3/bin:$PATH"

# Add Java home
export JAVA_HOME=$(/usr/libexec/java_home)

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='andy'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@github.com'

# Set my editor and git editor
export EDITOR="emacs -nw -q"
export GIT_EDITOR="emacs -nw -q"

# Set the path nginx
export NGINX_PATH='/opt/nginx'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

[ -e ${HOME}/.bash_local ] && source ${HOME}/.bash_local

