#!/bin/bash

set -e


error_exit(){
    echo "Send http://foaas.herokuapp.com/linus/Andy/<your-name> to Andy now!"
    exit 2
}

trap error_exit EXIT

source conf.sh
source toolchain.sh 
source $ANDY_INSTALL_DIR/util/functions.sh

not_implemented() {
    echo  "Not implemented!"
    exit 2
}

install_package() {
    not_implemented
}

install_script() {
    ./$1
}

if [ $# -eq 0 ]; then
    not_implemented
elif [ $1 -eq "package" ]; then
    install_package $2
elif [ $1 -eq "script" ]; then
    install_script $2
fi


